# Generated by Django 4.0 on 2024-05-21 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_user_is_email_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="terms_agreement",
        ),
    ]
