services:
  postgres-db:
    restart: always
    image: postgres:13-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/build
    ports:
      - "8000:8000"
    environment:
      - PG_HOST=postgres-db
      - POSTGRES_USER=${POSTGRES_USER}
    env_file:
      - .env
    depends_on:
      - postgres-db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-db