# Generated by Django 4.0 on 2024-05-05 22:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254)),
                ("exported", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
