# Generated by Django 4.0 on 2024-06-07 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0004_sitedetail_map_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="sitedetail",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
