# Generated by Django 4.0 on 2024-06-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_alter_category_slug_alter_product_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="colour",
            name="value",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="size",
            name="value",
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
