# Generated by Django 4.0 on 2024-06-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_alter_product_colours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sizes",
            field=models.ManyToManyField(related_name="products", to="shop.Size"),
        ),
    ]
