# Generated by Django 4.0 on 2024-07-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="phone_code",
            field=models.CharField(max_length=20),
        ),
    ]
