# Generated by Django 4.0 on 2024-07-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0019_remove_orderitem_unique_user_product_orderitems_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="orderitem",
            name="unique_user_product_orderitems",
        ),
        migrations.RemoveConstraint(
            model_name="orderitem",
            name="unique_guest_id_product_orderitems",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="ordered",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(
                fields=("user", "product", "ordered", "size_id", "color_id"),
                name="unique_user_product_orderitems",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(
                fields=("guest_id", "product", "ordered", "size_id", "color_id"),
                name="unique_guest_id_product_orderitems",
            ),
        ),
    ]
