# Generated by Django 4.0 on 2024-07-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0022_rename_payment_gateway_order_payment_method"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="orderitem",
            name="unique_user_product_orderitems",
        ),
        migrations.RemoveConstraint(
            model_name="orderitem",
            name="unique_guest_id_product_orderitems",
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("PROCESSING", "PROCESSING"),
                    ("SUCCESSFUL", "SUCCESSFUL"),
                    ("CANCELLED", "CANCELLED"),
                    ("FAILED", "FAILED"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(
                fields=("user", "product", "order_id", "size_id", "color_id"),
                name="unique_user_product_orderitems",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(
                fields=("guest_id", "product", "order_id", "size_id", "color_id"),
                name="unique_guest_id_product_orderitems",
            ),
        ),
    ]
