# Generated by Django 4.0 on 2024-07-18 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0023_remove_orderitem_unique_user_product_orderitems_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="expired",
        ),
        migrations.AddField(
            model_name="coupon",
            name="expiry_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="coupon",
            name="percentage_off",
            field=models.PositiveIntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
